#!/bin/bash
set -eu

if ! test -f $(which curl)
then
    echo "curl is not installed"
    exit
fi

curl -s https://github.com/kmille/dotfiles/blob/master/bash_aliases -o ~/.bash_aliases_chs
curl -s https://github.com/kmille/dotfiles/blob/master/vimrc -o ~/.vimrc
curl -s https://github.com/kmille/dotfiles/blob/master/tmux.conf -o ~/.tmux.conf

echo "Done. You're bash_aliases are at ~/.bash_aliases_chs"
